CREATE TABLE DOMAINEVENTENTRY
(
  AGGREGATEIDENTIFIER VARCHAR(255) NOT NULL,
  SEQUENCENUMBER      BIGINT       NOT NULL,
  TYPE                VARCHAR(255) NOT NULL,
  EVENTIDENTIFIER     VARCHAR(255) NOT NULL,
  PAYLOADREVISION     VARCHAR(255),
  PAYLOADTYPE         VARCHAR(255) NOT NULL,
  TIMESTAMP           VARCHAR(255) NOT NULL,
  METADATA            BLOB,
  PAYLOAD             BLOB         NOT NULL,
  CONSTRAINT PK_DOMAINEVENTENTRY PRIMARY KEY (AGGREGATEIDENTIFIER, SEQUENCENUMBER, TYPE)
);
CREATE UNIQUE INDEX UK_DOMAINEVENTENTRY_PK ON DOMAINEVENTENTRY (AGGREGATEIDENTIFIER, SEQUENCENUMBER, TYPE);
CREATE UNIQUE INDEX UK_DOMAINEVENTENTRY_EVENTIDENTIFIER ON DOMAINEVENTENTRY (EVENTIDENTIFIER);

-- Failed to load definition
-- [SQL0204] DB2LK_GENERATE_DDL in SYSPROC type *N not found.
-- auto-generated definition
CREATE TABLE SNAPSHOTEVENTENTRY
(
  AGGREGATEIDENTIFIER VARCHAR(255) NOT NULL,
  SEQUENCENUMBER      BIGINT       NOT NULL,
  TYPE                VARCHAR(255) NOT NULL,
  EVENTIDENTIFIER     VARCHAR(255) NOT NULL,
  PAYLOADREVISION     VARCHAR(255),
  PAYLOADTYPE         VARCHAR(255) NOT NULL,
  TIMESTAMP           VARCHAR(255) NOT NULL,
  METADATA            BLOB,
  PAYLOAD             BLOB         NOT NULL,
  CONSTRAINT PK_SNAPSHOTEVENTENTRY PRIMARY KEY (AGGREGATEIDENTIFIER, SEQUENCENUMBER, TYPE)
);
CREATE UNIQUE INDEX UK_SNAPSHOTEVENTENTRY_PK ON SNAPSHOTEVENTENTRY (AGGREGATEIDENTIFIER, SEQUENCENUMBER, TYPE);
CREATE UNIQUE INDEX UK_SNAPSHOTEVENTENTRY_EVENTIDENTIFIER ON SNAPSHOTEVENTENTRY (EVENTIDENTIFIER);